---
title: 'Alakazam: Analysis of aminoacid properties'
author: "Jason Anthony Vander Heiden"
date: '`r Sys.Date()`'
output:
  pdf_document:
    dev: pdf
    fig_height: 4
    fig_width: 7.5
    highlight: pygments
    toc: yes
  html_document:
    fig_height: 4
    fig_width: 7.5
    highlight: pygments
    theme: readable
    toc: yes
geometry: margin=1in
fontsize: 11pt
vignette: |
  %\VignetteIndexEntry{Aminoacid properties analysis} %\VignetteEngine{knitr::rmarkdown} %\usepackage[utf8]{inputenc}
---


Load Change-O data
--------------------------------------------------------------------------------
A small example Change-O tab-delimited database file is included in the 
`alakazam` package. 

```{r, eval=TRUE, warning=FALSE, message=FALSE}
library(alakazam)

# Load Change-O file
file <- system.file("extdata", "changeo_demo.tab", package="alakazam")
db <- readChangeoDb(file)
colnames(db)
```

Calculate amino acid properties of regions
-------------------------------------------
Multiple amino acid properties of a nucleotide or amino acide sequence can be obtained with the function `regionProperties`.  In this example we will retrieve the amino acid properties of the DNA `JUNCTION` sequences in the Change-O file. We will add a the prefix `JUNCTION` to the output column names.

```{r, eval=TRUE, warning=FALSE}
junction_properties <- regionProperties(db, seq="JUNCTION", nt=TRUE, trim=FALSE, label="JUNCTION")
head(junction_properties)
```

R Session information
-------
```{r}
sessionInfo()
```

