# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test DNA sequences for equality.
#' 
#' \code{rcpp_testSeqEqual} checks if two DNA sequences are identical.
#'
#' @param    seq1    character string containing a DNA sequence.
#' @param    seq2    character string containing a DNA sequence.
#' @param    ignore  vector of characters to ignore when testing for equality.
#' 
#' @return   Returns \code{TRUE} if sequences are equal and \code{FALSE} if they are not.
#'           Sequences of unequal length will always return \code{FALSE} regardless of
#'           their character values.
#' 
#' @seealso  Used by \link{collapseDuplicates}.
#' 
#' @examples
#' # Ignore gaps
#' rcpp_testSeqEqual("ATG-C", "AT--C")
#' rcpp_testSeqEqual("ATGGC", "ATGGN")
#' rcpp_testSeqEqual("AT--T", "ATGGC")
#' 
#' # Ignore only Ns
#' rcpp_testSeqEqual("ATG-C", "AT--C", ignore="N")
#' rcpp_testSeqEqual("ATGGC", "ATGGN", ignore="N")
#' rcpp_testSeqEqual("AT--T", "ATGGC", ignore="N")
#' @export
rcpp_testSeqEqual <- function(seq1, seq2, ignore = character()) {
    .Call('alakazam_rcpp_testSeqEqual', PACKAGE = 'alakazam', seq1, seq2, ignore)
}

#' @export
getDistanceMatrix <- function(rownames) {
    .Call('alakazam_getDistanceMatrix', PACKAGE = 'alakazam', rownames)
}

